//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\JOURNALS\BLOCK STYLER\CAVITY_MILL.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: dcard
//              Version: NX 2406
//              Date: 07-11-2026  (Format: mm-dd-yyyy)
//              Time: 12:44 (Format: hh-mm)
//
//  --- ALTERAÇÕES (Diogenes / PATHNC AUTOMATION) ---
//  1) Correção do bug: seleção de face não funcionava quando o projeto CAM era
//     criado do zero sobre a peça importada (peça vira COMPONENTE de um
//     assembly de manufatura), mas funcionava quando a peça já aberta apenas
//     era a Work Part. Faces agrupadas por OwningPart em ApplyCutAreaGeometry.
//  2) Escopo de seleção do face_select0 forçado para "Entire Assembly" em
//     runtime (EnableAssemblyScope), para permitir selecionar faces de
//     componentes mesmo que o .dlx tenha sido gerado com "Within Work Part".
//==============================================================================

using NXOpen;
using NXOpen.BlockStyler;
using NXOpen.CAM;
using NXOpen.UF;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

public class ROUGHINTERACTIVE
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.ListBox list_box0;// Block type: List Box
    private NXOpen.BlockStyler.IntegerBlock integerCutDepth;// Block type: Integer
    private NXOpen.BlockStyler.IntegerBlock integerRpm;// Block type: Integer
    private NXOpen.BlockStyler.IntegerBlock integerFeedRate;// Block type: Integer
    private NXOpen.BlockStyler.FaceCollector face_select0;// Block type: Face Collector

    private const bool DEBUG_MODE = false;

    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int SnapPointTypesEnabled_PointonCurve = (1 << 10);
    public static readonly int SnapPointTypesEnabled_PointonSurface = (1 << 11);
    public static readonly int SnapPointTypesEnabled_PointConstructor = (1 << 12);
    public static readonly int SnapPointTypesEnabled_TwocurveIntersection = (1 << 13);
    public static readonly int SnapPointTypesEnabled_TangentPoint = (1 << 14);
    public static readonly int SnapPointTypesEnabled_Poles = (1 << 15);
    public static readonly int SnapPointTypesEnabled_BoundedGridPoint = (1 << 16);
    public static readonly int SnapPointTypesEnabled_FacetVertexPoint = (1 << 17);
    public static readonly int SnapPointTypesEnabled_DefiningPoint = (1 << 18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int SnapPointTypesOnByDefault_PointonCurve = (1 << 10);
    public static readonly int SnapPointTypesOnByDefault_PointonSurface = (1 << 11);
    public static readonly int SnapPointTypesOnByDefault_PointConstructor = (1 << 12);
    public static readonly int SnapPointTypesOnByDefault_BoundedGridPoint = (1 << 16);
    public static readonly int SnapPointTypesOnByDefault_FacetVertexPoint = (1 << 17);
    //------------------------------------------------------------------------------
    //Bit Option for Property: EntityType
    //------------------------------------------------------------------------------
    public static readonly int EntityType_AllowFaces = (1 << 4);
    public static readonly int EntityType_AllowDatums = (1 << 5);
    public static readonly int EntityType_AllowBodies = (1 << 6);
    //------------------------------------------------------------------------------
    //Bit Option for Property: FaceRules
    //------------------------------------------------------------------------------
    public static readonly int FaceRules_SingleFace = (1 << 0);
    public static readonly int FaceRules_RegionFaces = (1 << 1);
    public static readonly int FaceRules_TangentFaces = (1 << 2);
    public static readonly int FaceRules_TangentRegionFaces = (1 << 3);
    public static readonly int FaceRules_BodyFaces = (1 << 4);
    public static readonly int FaceRules_FeatureFaces = (1 << 5);
    public static readonly int FaceRules_AdjacentFaces = (1 << 6);
    public static readonly int FaceRules_ConnectedBlendFaces = (1 << 7);
    public static readonly int FaceRules_AllBlendFaces = (1 << 8);
    public static readonly int FaceRules_RibFaces = (1 << 9);
    public static readonly int FaceRules_SlotFaces = (1 << 10);
    public static readonly int FaceRules_BossandPocketFaces = (1 << 11);
    public static readonly int FaceRules_MergedRibFaces = (1 << 12);
    public static readonly int FaceRules_RegionBoundaryFaces = (1 << 13);
    public static readonly int FaceRules_FaceandAdjacentFaces = (1 << 14);
    public static readonly int FaceRules_HoleFaces = (1 << 15);
    public static readonly int FaceRules_CurvatureCrossSectionFaces = (1 << 16);
    public static readonly int FaceRules_FloodFillFaces = (1 << 17);

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public ROUGHINTERACTIVE()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();

            // Caminho resolvido em runtime, relativo a onde a DLL está rodando.
            // Substitui o caminho fixo "D:\JOURNALS\BLOCK STYLER\CAVITY_MILL.dlx".
            // Coloque o CAVITY_MILL.dlx dentro de uma pasta "Resources" ao lado
            // da DLL compilada (Build Action = Content, Copy to Output Directory
            // = Copy if newer).
            string assemblyDir = System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            theDlxFileName = System.IO.Path.Combine(assemblyDir, "Resources", "CAVITY_MILL.dlx");

            if (!File.Exists(theDlxFileName))
                throw new FileNotFoundException("Arquivo .dlx não encontrado em: " + theDlxFileName);

            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception)
        {
            throw;
        }
    }

    public static void Run()
    {
        ROUGHINTERACTIVE theROUGHINTERACTIVE = null;
        try
        {
            theROUGHINTERACTIVE = new ROUGHINTERACTIVE();
            theROUGHINTERACTIVE.Launch();
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if (theROUGHINTERACTIVE != null)
                theROUGHINTERACTIVE.Dispose();
            theROUGHINTERACTIVE = null;
        }
    }

    public static int GetUnloadOption(string arg)
    {
        return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
    }

    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
    {
        NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
        try
        {
            dialogResponse = theDialog.Launch();
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return dialogResponse;
    }

    public void Dispose()
    {
        if (theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }

    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------

    public void initialize_cb()
    {
        try
        {
            list_box0 = (NXOpen.BlockStyler.ListBox)theDialog.TopBlock.FindBlock("list_box0");
            integerCutDepth = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("integerCutDepth");
            integerRpm = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("integerRpm");
            integerFeedRate = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("integerFeedRate");
            face_select0 = (NXOpen.BlockStyler.FaceCollector)theDialog.TopBlock.FindBlock("face_select0");

            // ── Libera seleção de faces em componentes do assembly ──
            EnableAssemblyScope(face_select0);

            // ── Popula a lista com as ferramentas disponíveis na biblioteca ──
            PopulateToolListBox();

            if (DEBUG_MODE)
                LogPartsDebug(null);
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            RunCavityMill();
        }
        catch (Exception ex)
        {
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist = null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }

    // ==============================================================================
    //  ESCOPO DE SELEÇÃO
    // ==============================================================================

    // Força o escopo de seleção do bloco para "Entire Assembly", permitindo
    // selecionar faces de componentes quando o setup CAM é um assembly.
    // Equivale ao Selection.SelectionScope.AnyInAssembly do SelectionManager.
    // Usa GetEnumMembers para não depender do texto exato da versão do NX.
    // Se a propriedade não existir nesta versão, ajuste "Scope" diretamente
    // no CAVITY_MILL.dlx (Block UI Styler > face_select0 > Scope).



    private void EnableAssemblyScope(NXOpen.BlockStyler.UIBlock block)
    {
        if (block == null) return;
        PropertyList props = block.GetProperties();

        string[] candidates = { "Scope", "SelectionScope", "SelScope", "Selection Scope" };
        foreach (string name in candidates)
        {
            try
            {
                string[] members = props.GetEnumMembers(name);
                for (int i = 0; i < members.Length; i++)
                {
                    if (members[i].IndexOf("Assembly", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        props.SetEnum(name, i);
                        return;
                    }
                }
            }
            catch { /* tenta o próximo nome */ }
        }

        // Nada funcionou: mostra as propriedades disponíveis (sempre, sem DEBUG_MODE)
        string[] all = props.GetPropertyNames();
        theUI.NXMessageBox.Show("Scope não encontrado", NXMessageBox.DialogType.Information,
            "Propriedades do bloco face_select0:\n" + string.Join("\n", all));
    }
    // ==============================================================================
    //  LÓGICA DE NEGÓCIO (Cavity Mill) — abaixo, tudo escrito à mão, refatorado
    //  em métodos pequenos e reutilizáveis.
    // ==============================================================================

    // ── Configuração dos nomes fixos usados na montagem CAM (ajuste aqui se mudar) ──
    private const string NCGROUP_PROGRAM = "PROGRAM";
    private const string NCGROUP_METHOD = "MILL_ROUGH";
    private const string WORKPIECE_NAME = "WORKPIECE";
    private const string OPERATION_TEMPLATE = "mill_contour";
    private const string OPERATION_SUBTYPE = "CAVITY_MILL";

    // Nome de propriedade que expõe os itens selecionados do list_box0 nesta
    // versão do NX (2406). Se você trocar de versão e o list box parar de
    // retornar seleção, esse é o primeiro lugar a checar.
    private const string LISTBOX_SELECTION_PROPERTY = "SelectedItems";

    // Prefixos de nome usados na sua biblioteca para ferramentas de desbaste
    // (Cavity Mill). Ajuste/adicione aqui se criar novas famílias de ferramenta.
    // Ex: "ENDMILL_D18MM", "CUTTER_D25_R.8".
    private static readonly string[] ROUGHING_TOOL_PREFIXES = { "CUTTER_", "ENDMILL_" };

    // Verifica se o nome da ferramenta bate com algum dos prefixos de desbaste.
    private static bool IsRoughingTool(string toolName)
    {
        foreach (string prefix in ROUGHING_TOOL_PREFIXES)
        {
            if (toolName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                return true;
        }
        return false;
    }

    // Lê as ferramentas do CAMGroupCollection e popula o list_box0, mostrando
    // somente as ferramentas de desbaste (CUTTER_ e ENDMILL_), já que são as
    // que você normalmente usa no Cavity Mill. Precisa rodar no initialize_cb()
    // - se rodar só no ok_cb(), o diálogo já fecha antes de você ver a lista populada.
    private void PopulateToolListBox()
    {
        NXOpen.Part workPart = theSession.Parts.Work;
        if (workPart == null || list_box0 == null)
            return;

        List<string> toolNames = new List<string>();
        foreach (NXOpen.CAM.Tool tool in GetAllTools(workPart))
        {
            if (IsRoughingTool(tool.Name))
                toolNames.Add(tool.Name);
        }

        toolNames.Sort();
        list_box0.GetProperties().SetStrings("ListItems", toolNames.ToArray());

        if (toolNames.Count == 0)
            ShowError("Nenhuma ferramenta CUTTER_ ou ENDMILL_ encontrada na biblioteca desta peça.");
    }

    // Percorre o CAMGroupCollection e retorna todos os objetos do tipo Tool.
    private static IEnumerable<NXOpen.CAM.Tool> GetAllTools(NXOpen.Part workPart)
    {
        foreach (NXOpen.CAM.CAMObject obj in workPart.CAMSetup.CAMGroupCollection.ToArray())
        {
            NXOpen.CAM.Tool tool = obj as NXOpen.CAM.Tool;
            if (tool != null)
                yield return tool;
        }
    }

    // Busca um NCGroup pelo nome, mas só entre os objetos que realmente são do
    // tipo T pedido (Method, NCGroup de Program, FeatureGeometry, etc). Evita o
    // erro "Unable to cast object of type NCGroup to type X", que acontece
    // quando FindObject acha um grupo de OUTRA categoria com o mesmo nome
    // (ex: "NONE" existindo tanto em Method quanto em outra view).
    private static T FindGroupByNameAndType<T>(NXOpen.Part workPart, string groupName) where T : class
    {
        foreach (NXOpen.CAM.CAMObject obj in workPart.CAMSetup.CAMGroupCollection.ToArray())
        {
            NXOpen.CAM.NCGroup group = obj as NXOpen.CAM.NCGroup;
            if (group == null || !string.Equals(group.Name, groupName, StringComparison.OrdinalIgnoreCase))
                continue;

            T match = obj as T;
            if (match != null)
                return match;
        }
        return null;
    }

    // Busca ferramenta pelo nome sem usar FindObject (que lança exceção se não achar).
    private static NXOpen.CAM.Tool FindToolByName(NXOpen.Part workPart, string toolName)
    {
        foreach (NXOpen.CAM.Tool tool in GetAllTools(workPart))
        {
            if (string.Equals(tool.Name, toolName, StringComparison.OrdinalIgnoreCase))
                return tool;
        }
        return null;
    }

    // Lê o(s) item(ns) selecionado(s) do list_box0. Tenta primeiro a propriedade
    // já validada para esta versão do NX; se não vier nada (versão diferente,
    // nome mudou), cai no fallback por índices selecionados.
    private string[] GetListBoxSelectedItems(NXOpen.BlockStyler.ListBox listBox)
    {
        PropertyList props = listBox.GetProperties();

        try
        {
            string[] result = props.GetStrings(LISTBOX_SELECTION_PROPERTY);
            if (result != null && result.Length > 0)
                return result;
        }
        catch { /* propriedade não existe nesta versão - segue pro fallback */ }

        // Fallback: lê como índices selecionados e converte para os textos da lista.
        try
        {
            int[] selectedIndices = props.GetIntegerVector("SelectedItems");
            string[] allItems = props.GetStrings("ListItems");

            if (selectedIndices != null && allItems != null && selectedIndices.Length > 0)
            {
                string[] result = new string[selectedIndices.Length];
                for (int i = 0; i < selectedIndices.Length; i++)
                    result[i] = allItems[selectedIndices[i]];
                return result;
            }
        }
        catch { /* segue pro retorno vazio abaixo */ }

        return new string[0];
    }

    // Mostra um erro padronizado no NXMessageBox.
    private void ShowError(string message)
    {
        theUI.NXMessageBox.Show("Cavity Mill", NXMessageBox.DialogType.Error, message);
    }

    // Monta um nome de operação único a partir do nome da ferramenta usada,
    // evitando colisão quando houver várias operações em sequência.
    private static string BuildOperationName(string toolName)
    {
        return OPERATION_SUBTYPE + "_" + toolName;
    }

    // Resolve a ferramenta selecionada no list_box0. Retorna null (e mostra o
    // erro correspondente) se nada estiver selecionado ou a ferramenta não existir.
    private NXOpen.CAM.Tool GetSelectedTool(NXOpen.Part workPart)
    {
        string[] selected = GetListBoxSelectedItems(list_box0);

        if (selected.Length == 0)
        {
            ShowError("Selecione uma ferramenta na lista antes de continuar.");
            return null;
        }

        NXOpen.CAM.Tool tool = FindToolByName(workPart, selected[0]);

        if (tool == null)
            ShowError("Ferramenta '" + selected[0] + "' não encontrada na biblioteca.");

        return tool;
    }

    // Resolve as faces selecionadas no face_select0. Retorna array vazio (e
    // mostra o erro correspondente) se nada estiver selecionado.
    //
    // NOTA (fix assembly): em projetos CAM criados sobre a peça importada
    // como componente de um assembly, as faces aqui retornadas normalmente
    // têm face.OwningPart != theSession.Parts.Work. Isso é esperado e é
    // tratado em ApplyCutAreaGeometry — não filtre nem descarte essas faces
    // aqui.
    private NXOpen.Face[] GetSelectedFaces()
    {
        NXOpen.TaggedObject[] selected = face_select0.GetSelectedObjects();

        if (selected == null || selected.Length == 0)
        {
            ShowError(
                "Selecione ao menos uma face antes de continuar.\n\n" +
                "Se você está num projeto CAM criado sobre a peça importada " +
                "(peça como componente de assembly), confirme que o Face " +
                "Collector do diálogo permite seleção em componentes " +
                "(escopo 'Entire Assembly'), e não apenas na Work Part.");
            return new NXOpen.Face[0];
        }

        NXOpen.Face[] faces = new NXOpen.Face[selected.Length];
        for (int i = 0; i < selected.Length; i++)
            faces[i] = (NXOpen.Face)selected[i];

        if (DEBUG_MODE)
            LogPartsDebug(faces);

        return faces;
    }

    // Aplica as faces selecionadas como Cut Area Geometry da operação.
    //
    // FIX: antes, a regra era SEMPRE criada com workPart.ScRuleFactory,
    // assumindo que toda face pertence à Work Part. Isso falha quando o
    // projeto CAM foi montado como assembly e a peça original virou
    // componente — nesse caso face.OwningPart aponta pra part do
    // componente, não pra workPart (o assembly).
    //
    // Agora agrupamos as faces por OwningPart e criamos uma FaceDumbRule
    // por dono, usando ownerPart.ScRuleFactory (não workPart.ScRuleFactory)
    // em cada grupo. Isso funciona tanto no cenário "peça sozinha" (onde
    // haverá só um grupo, igual a workPart) quanto no cenário "assembly"
    // (onde haverá um grupo por component part envolvida na seleção).
    private void ApplyCutAreaGeometry(NXOpen.Part workPart, NXOpen.CAM.CavityMillingBuilder builder, NXOpen.Face[] faces)
    {
        builder.CutAreaGeometry.InitializeData(false);

        NXOpen.CAM.GeometrySet geomSet = (NXOpen.CAM.GeometrySet)builder.CutAreaGeometry.GeometryList.FindItem(0);

        // Agrupa as faces pela part que realmente as possui.
        Dictionary<NXOpen.Part, List<NXOpen.Face>> facesByOwner = new Dictionary<NXOpen.Part, List<NXOpen.Face>>();
        foreach (NXOpen.Face f in faces)
        {
            NXOpen.Part owner = f.OwningPart as NXOpen.Part;
            if (owner == null)
                owner = workPart; // fallback de segurança, não deveria acontecer

            if (!facesByOwner.ContainsKey(owner))
                facesByOwner[owner] = new List<NXOpen.Face>();

            facesByOwner[owner].Add(f);
        }

        List<NXOpen.SelectionIntentRule> rules = new List<NXOpen.SelectionIntentRule>();

        foreach (KeyValuePair<NXOpen.Part, List<NXOpen.Face>> kvp in facesByOwner)
        {
            NXOpen.Part ownerPart = kvp.Key;
            NXOpen.Face[] ownerFaces = kvp.Value.ToArray();

            NXOpen.SelectionIntentRuleOptions ruleOptions = ownerPart.ScRuleFactory.CreateRuleOptions();
            ruleOptions.SetSelectedFromInactive(true);

            NXOpen.FaceDumbRule faceRule = ownerPart.ScRuleFactory.CreateRuleFaceDumb(ownerFaces, ruleOptions);
            ruleOptions.Dispose();

            rules.Add(faceRule);
        }

        if (rules.Count == 0)
        {
            ShowError("Não foi possível montar a(s) regra(s) de seleção de face (nenhuma face válida encontrada).");
            return;
        }

        geomSet.ScCollector.ReplaceRules(rules.ToArray(), false);
    }

    // Helper de diagnóstico: mostra Work Part, Display Part, e (se fornecido
    // um array de faces) a part dona de cada face selecionada. Ative via
    // DEBUG_MODE para confirmar rapidamente se o cenário é o de assembly.
    private void LogPartsDebug(NXOpen.Face[] faces)
    {
        NXOpen.Part workPart = theSession.Parts.Work;
        NXOpen.Part dispPart = theSession.Parts.Display;

        System.Text.StringBuilder sb = new System.Text.StringBuilder();
        sb.AppendLine("Work Part:    " + (workPart != null ? workPart.Name : "(null)"));
        sb.AppendLine("Display Part: " + (dispPart != null ? dispPart.Name : "(null)"));

        if (workPart != null && dispPart != null && !string.Equals(workPart.Name, dispPart.Name, StringComparison.OrdinalIgnoreCase))
            sb.AppendLine("=> Work Part e Display Part SÃO DIFERENTES (cenário de assembly provável).");

        if (faces != null && faces.Length > 0)
        {
            sb.AppendLine();
            sb.AppendLine("Faces selecionadas (" + faces.Length + "):");
            for (int i = 0; i < faces.Length; i++)
            {
                NXOpen.Part owner = faces[i].OwningPart as NXOpen.Part;
                string ownerName = owner != null ? owner.Name : "(desconhecida)";
                bool diff = workPart != null && owner != null && !string.Equals(owner.Name, workPart.Name, StringComparison.OrdinalIgnoreCase);
                sb.AppendLine("  Face " + i + " -> OwningPart: " + ownerName + (diff ? "  [DIFERENTE DA WORK PART]" : ""));
            }
        }

        theUI.NXMessageBox.Show("Debug - Parts", NXMessageBox.DialogType.Information, sb.ToString());
    }

    // Aplica os parâmetros padrão de non-cutting / cut pattern da operação.
    private void ConfigureDefaults(NXOpen.CAM.CavityMillingBuilder builder)
    {
        builder.NonCuttingBuilder.EngageClosedAreaBuilder.EngRetType = NXOpen.CAM.NcmPlanarEngRetBuilder.EngRetTypes.RampOnShape;
        builder.NonCuttingBuilder.EngageClosedAreaBuilder.HelicalRampAngleBuilder.Value = 1.0;
        builder.NonCuttingBuilder.TransferWithinLevelsType = NXOpen.CAM.NcmPlanarBuilder.TransferWithinLevelsTypes.PrevPlane;
        builder.NonCuttingBuilder.TransferWithinLevelsSafeDistanceBuilder.Value = 0.5;
        builder.NonCuttingBuilder.TransferBetweenRegionsBuilder.Type = NXOpen.CAM.NcmTransfer.TransferTypes.PrevPlane;
        builder.NonCuttingBuilder.TransferBetweenRegionsBuilder.SafeDistanceBuilder.Value = 0.0;
        builder.NonCuttingBuilder.ClearanceBuilder.ClearanceType = NXOpen.CAM.NcmClearanceBuilder.ClearanceTypes.Automatic;
        builder.NonCuttingBuilder.ClearanceBuilder.SafeDistance = 10.0;

        builder.CutPattern.CutPattern = NXOpen.CAM.CutPatternBuilder.Types.FollowPeriphery;
        builder.BndStepover.PercentToolFlatBuilder.Value = 50.0;
        builder.CutLevel.ApplyGlobalDepthPerCut();
        builder.CutParameters.IpwType = NXOpen.CAM.CutParametersIpwTypes.None;
        builder.CutParameters.TrimControl = NXOpen.CAM.CutParametersTrimControlTypes.Silhoutte;
        builder.CutParameters.PartStock.Value = 0.5;
        builder.CutParameters.CutOrder = NXOpen.CAM.CutParametersCutOrderTypes.DepthFirst;
    }

    // Aplica os valores vindos da UI (profundidade de corte, RPM, feed rate).
    private void ApplyUIValues(NXOpen.CAM.CavityMillingBuilder builder)
    {
        builder.CutLevel.GlobalDepthPerCut.DistanceBuilder.Value = integerCutDepth.Value;
        builder.FeedsBuilder.SpindleRpmBuilder.Value = integerRpm.Value;
        builder.FeedsBuilder.FeedCutBuilder.Value = integerFeedRate.Value;
    }

    // Cria a operação de Cavity Mill usando a ferramenta selecionada na lista,
    // as faces selecionadas, e os valores digitados nos campos da UI.
    private void RunCavityMill()
    {
        NXOpen.Part workPart = theSession.Parts.Work;

        NXOpen.CAM.Tool tool = GetSelectedTool(workPart);
        if (tool == null)
            return;

        NXOpen.Face[] faces = GetSelectedFaces();
        if (faces.Length == 0)
            return;

        NXOpen.CAM.NCGroup ncProgram = FindGroupByNameAndType<NXOpen.CAM.NCGroup>(workPart, NCGROUP_PROGRAM);
        NXOpen.CAM.Method method = FindGroupByNameAndType<NXOpen.CAM.Method>(workPart, NCGROUP_METHOD);
        NXOpen.CAM.FeatureGeometry workpiece = FindGroupByNameAndType<NXOpen.CAM.FeatureGeometry>(workPart, WORKPIECE_NAME);

        if (ncProgram == null || method == null || workpiece == null)
        {
            ShowError(
                "Não foi possível localizar um ou mais grupos CAM esperados.\n" +
                "Program: " + NCGROUP_PROGRAM + " -> " + (ncProgram == null ? "NÃO ENCONTRADO" : "OK") + "\n" +
                "Method:  " + NCGROUP_METHOD + " -> " + (method == null ? "NÃO ENCONTRADO" : "OK") + "\n" +
                "Workpiece: " + WORKPIECE_NAME + " -> " + (workpiece == null ? "NÃO ENCONTRADO" : "OK") + "\n" +
                "Confira os nomes reais no Operation Navigator (Program Order, Machine Method e Geometry View).");
            return;
        }

        string operationName = BuildOperationName(tool.Name);

        NXOpen.CAM.Operation operation = workPart.CAMSetup.CAMOperationCollection.CreateWithUserName(
            ncProgram, method, tool, workpiece,
            OPERATION_TEMPLATE, OPERATION_SUBTYPE,
            NXOpen.CAM.OperationCollection.UseDefaultName.False,
            operationName, operationName);

        NXOpen.CAM.CavityMillingBuilder builder =
            workPart.CAMSetup.CAMOperationCollection.CreateCavityMillingBuilder((NXOpen.CAM.CavityMilling)operation);

        ConfigureDefaults(builder);
        ApplyUIValues(builder);
        ApplyCutAreaGeometry(workPart, builder, faces);

        NXOpen.CAM.CavityMilling committed = (NXOpen.CAM.CavityMilling)builder.Commit();
        workPart.CAMSetup.GenerateToolPath(new NXOpen.CAM.CAMObject[] { committed });


        System.Windows.Forms.Application.DoEvents();

        builder.Destroy();

        UFSession theUFSession = UFSession.GetUFSession();
        theUFSession.Disp.Refresh();
    }
}